### ISSUE TITLE
Kann keine Startliste erstellen. Bei Ergebnisse habe ich die Wertung schon angelegt

### ISSUE THREAD

**Issue by RobertEschment** [Feuerwehrsport/feusport#14]
![IMG-20240704-WA0015](https://github.com/Feuerwehrsport/feusport/assets/174749051/3a2e8719-1c75-40ff-b533-6839e70477ba)

**Comment by georf** [comment]
Ich glaube, du hattest einen ganz anderen Fehler gefunden. Du hast eine Wertung aus einem anderen Wettkampf genommen, weshalb der Wettkampf komplett verhunzt ist. Das kannst du jetzt nicht mehr machen und somit sollte das mit den Startlisten auch beim nächsten Mal funktionieren.
