### ISSUE TITLE
Ergebnislisten erzeugen

### ISSUE THREAD

**Issue by Antonia-MOL** [Feuerwehrsport/feusport#15]
Bei der Erstellung einer neuen Wertung kann man ja ankreuzen das eine Ergebnisliste dazu erzeugt werden soll, leider ist keine entsprechende Liste danach zu finden. 
Falls das automatisch passieren soll, sobald da ein Häkchen drin ist, dann klappt das leider noch nicht.
Falls es nicht automatisch erzeugt werden soll, dann müsste man den Erklärungstext eventuell umschreiben, da das sonst etwas missverständlich ist. 

(Habe es jetzt nur Mobil getestet!)

**Comment by georf** [comment]
Das kann ich bestätigen. Das funktioniert nicht.
