### ISSUE TITLE
Neue Registerkarte beim öffnen von Dokumenten

### ISSUE THREAD

**Issue by sebaMV112** [Feuerwehrsport/feusport#27]
Öffnen der Urkunden nach dem Erstellen, sowie öffnen weiterer Unterlagen in einer neuen Registerkarte, um die Weiterarbeit auf der Website zu ermöglichen.

**Comment by georf** [comment]
Ich habe die Links durchgeguckt. Eigentlich sollte das nur bei den Urkunden vorgekommen sein. Die restlichen PDFs sollten schon im neuen Tab aufgehen.

Bei den Urkunden habe ich es auch angepasst.

Wenn dir noch was auffällt, kannst du gerne ein neues Ticket machen.
