### ISSUE TITLE
Startliste mit Bahnzuweisung für Wertungsgruppe

### ISSUE THREAD

**Issue by Antonia-MOL** [Feuerwehrsport/feusport#31]
Bei einigen Disziplinen ist es möglich eine Startliste mit "Bahn abhängig von Wertungsgruppen" zu erstellen. 
Leider werden dann alle Wertungsgruppen die irgendwie möglich wären (egal welche man für den Wettkampf nutzt) angezeigt und man muss die richtige finden. 
Könnte man hier entweder die Disziplin hinter der Wertungsgruppe vermerken oder nur die für die ausgewählte Disziplin anzeigen lassen? 

![grafik](https://github.com/user-attachments/assets/23c9aba0-c0e4-461c-9ac9-c53f5b361613)

**Comment by georf** [comment]
Ist direkt live behoben.
