### ISSUE TITLE
frei belegbare Haken in der Mannschaftsübersicht

### ISSUE THREAD

**Issue by raznzsnasna** [Feuerwehrsport/feusport#46]
In deinem Online- Seminar erinnerten wir dich daran, dass es in der Mannschaftsauswahl frei verfügbare Haken gab.
Wenn man dann noch eine zweite / dritte Hakenspalte einfügen und frei benennen kann. Das wäre toll.
Liebe Grüße

**Comment by georf** [comment]
Danke für die Erinnerung. Ich habe mich gleich mal rangesetzt. Ich schreibe die Ergebnisse ins Ticket #47. Ihr wart beide fast gleichzeitig mit dem Reinschreiben.
