### ISSUE TITLE
Checkliste für die Anmeldung der Mannschaften am Wettkampftag vor Ort

### ISSUE THREAD

**Issue by gauers79** [Feuerwehrsport/feusport#47]
Es wäre schön wieder eine oder ggf. mehrere Checkboxen auf der Seite der Mannschaften zu haben.
Das hilft einem einen Überblick am Wettkampftag vor dem Start zu bekommen.
Nutzungsmöglichkeiten:

- Mannschaft ist angereist 
oder
- Mannschaft hat bezahlt 

Ggf. kann man dann langfristig auch über einen Button "Anreise schließen" die Option anbieten die fehlenden Mannschaften aus den Startlisten herauszunehmen?

**Comment by georf** [comment]
Danke für die Erinnerung. Ich habe mich gleich mal rangesetzt.

Als Ergebnis gibt es nun im erweiterten Menü eine Punkt "Mannschaftsspalten". Dort könnt ihr verschiedene Spalten pflegen, die auch unterschiedliche Werte haben können. Dann könnt ihr in der Mannschaftsübersicht die Mannschaften direkt abhaken oder es auf der Mannschaftsseite auch machen.

Neue Wettkämpfe haben immer automatisch einen Wert "Angereist?" drin. Bei den zukünftigen Wettkämpfen habe ich das auch ergänzt. Bei den vergangenen habe ich es jetzt nicht gemacht. Ihr könnt das aber gerne mal mit einem versteckten Wettkampf testen.

Ich habe auch über den Vorschlag der automatischen Entfernung aus der Startliste nachgedacht, aber diesen Punkt wieder verworfen. Im Besten Falle bleiben ja nur wenige Mannschaften übrig. Wenn man sie komplett löscht, verschwinden sie auch aus der Startliste.
