### ISSUE TITLE
Wertungen

### ISSUE THREAD

**Issue by sebaMV112** [Feuerwehrsport/feusport#5]
Derzeit sind nur TGL und DIN als Wertungen auszuwählen. Hier sollte die Auswahl noch erweitert werden (Sport, Einsatz,...)

**Comment by georf** [comment]
Ich habe "Sport und Einsatz" auch direkt zur Auswahl gestellt. Außerdem habe ich die Hinweise darauf ergänzt, dass man später auch noch mehr ohne Vorlage machen kann.

Wenn das so reicht, kannst du das Ticket gerne schließen ;-)
