### ISSUE TITLE
Löschfunktion

### ISSUE THREAD

**Issue by Antonia-MOL** [Feuerwehrsport/feusport#6]
Aktuell kann keine Startliste gelöscht werden, egal ob ich es über den Rechner probiere oder übers Smartphone. 

Außerdem ist es in der mobilen Ansicht nicht möglich eine Mannschaft zu löschen oder einen Wettkämpfer aus der Mannschaft zu löschen.
Beides ist aktuell nur über den Rechner möglich.

**Comment by georf** [comment]
Startlisten können nun auch gelöscht werden.

Die Smartphone-Sache gucke ich mir mal an.

**Comment by georf** [comment]
Probiere das bitte nochmal aus. Bei mir hat das ohne Probleme auf dem Smartphone funktioniert.

**Comment by Antonia-MOL** [comment]
Jetzt klappt alles. 👍🏻
